// Code generated by "stringer -type=PacketType"; DO NOT EDIT.

package zinc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Error-0]
	_ = x[Ping-1]
	_ = x[Pong-2]
	_ = x[PeerInfoRequest-3]
	_ = x[PeerInfoResponse-4]
}

const _PacketType_name = "ErrorPingPongPeerInfoRequestPeerInfoResponse"

var _PacketType_index = [...]uint8{0, 5, 9, 13, 28, 44}

func (i PacketType) String() string {
	if i >= PacketType(len(_PacketType_index)-1) {
		return "PacketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PacketType_name[_PacketType_index[i]:_PacketType_index[i+1]]
}
